### ISSUE TITLE
Implementation of y_anchor at Tx is inconsistent with the paper

### ISSUE THREAD

**Issue by asdLeaving** [wsxtyrdd/NTSCC_plus#6]
In Sec. III of the paper, the y_anchor at Tx is estimated by averaging _n_ independent realizations of channel and decoding process. However, the implementation of forward function of NTSCC_plus is adding a uniform quantization noise as follows.
```
        y_tilde = self.ntc.gaussian_conditional.quantize(y, "noise")
        y_half = y_tilde.clone()
        x_hat_ntc = self.ntc.g_s(y_tilde)

        y_half[:, :, 0::2, 0::2] = 0
        y_half[:, :, 1::2, 1::2] = 0
        sc_params = self.ntc.sc_transform(y_half)
        sc_params[:, :, 0::2, 1::2] = 0
        sc_params[:, :, 1::2, 0::2] = 0
        gaussian_params = self.ntc.entropy_parameters(
            torch.cat((params, sc_params), dim=1)
        )
```
I wonder if this inconsistency affects performance.

**Comment by wsxtyrdd** [comment]
It seems there might be a misunderstanding regarding the selected lines. 
In this context, uniform noise is utilized solely for the purpose of entropy estimation. Please refer to the work by Ballé, Johannes, Valero Laparra, and Eero P. Simoncelli, titled "End-to-end optimized image compression," for a detailed explanation.

Since y itself is a continuous variable, its entropy (not differential entropy) is theoretically infinite. In our case, we employ the entropy of quantized y (achieved by adding uniform noise) as a proxy for patch-wise bandwidth allocation.

**Comment by asdLeaving** [comment]
> It seems there might be a misunderstanding regarding the selected lines. In this context, uniform noise is utilized solely for the purpose of entropy estimation. Please refer to the work by Ballé, Johannes, Valero Laparra, and Eero P. Simoncelli, titled "End-to-end optimized image compression," for a detailed explanation.
> 
> Since y itself is a continuous variable, its entropy (not differential entropy) is theoretically infinite. In our case, we employ the entropy of quantized y (achieved by adding uniform noise) as a proxy for patch-wise bandwidth allocation.

My doubt is not on the calculation of entropy estimation and bandwidth allocation, rather it is about the anchor part of the latent feature $y_A$. Sec. III of the paper claims that the transmitter should conduct _n_ independent realizations of channel and decoding as in Eq.(10), but there seems no code to implement that. The code just uses the noised y_half (the clone of y_tilde, not affected by channel and decoder) to calculate spatial context later used for decoding the non-anchor part.

**Comment by wsxtyrdd** [comment]
I apologize for the delayed response, and you are correct in your observation. Indeed, the transmitter does not perform local simulations as outlined in Eq.(10), primarily because the gains are minimal and it would significantly increase the inference time. I regret that this point was not clearly articulated in the paper.

This issue represents a key challenge in end-to-end transmission systems, differing from the separate source channel approaches in that the features at the transmitting and receiving ends are not synchronized. This desynchronization mainly impacts video transmission, leading to error accumulation and reducing the effectiveness of inter-frame encoding, especially when the Group of Pictures (GOP) size is large.
